// File generated by hand to mirror the shape of `flutterfire configure` output.
// All values here are STUBS — replace with real FlutterFire-generated config in
// Session 4 before launch. Until then, FCM init is wrapped in a try/catch in
// PushService and silently noops.
//
// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// STUB: Replace with real FlutterFire-generated config in Session 4 before launch.
///
/// To regenerate for real:
/// ```
/// dart pub global activate flutterfire_cli
/// flutterfire configure --project=<your-real-firebase-project>
/// ```
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'PackPath does not support web — Firebase web options are not stubbed.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'PackPath does not support ${defaultTargetPlatform.name}.',
        );
    }
  }

  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: 'AIzaSyD-stub-key-not-real-replace-in-session-4',
    appId: '1:000000000000:android:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'packpath-stub',
    storageBucket: 'packpath-stub.appspot.com',
  );

  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: 'AIzaSyD-stub-key-not-real-replace-in-session-4',
    appId: '1:000000000000:ios:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'packpath-stub',
    storageBucket: 'packpath-stub.appspot.com',
    iosBundleId: 'app.packpath.mobile',
  );
}
